# Generated by Django 4.2.2 on 2023-06-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('show_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('user_id', 'show_id')},
            },
        ),
    ]
